name: flutter_simple_country_picker

description: An easy-to-use country selection widget for Flutter. Allows users to select a country from a comprehensive list. Supports Android, iOS, web, Windows and Linux platforms.

version: 0.6.4

homepage: https://github.com/ziqq/flutter_simple_country_picker

repository: https://github.com/ziqq/flutter_simple_country_picker

issue_tracker: https://github.com/ziqq/flutter_simple_country_picker/issues

funding:
  - https://www.buymeacoffee.com/ziqq
  - https://boosty.to/ziqq

topics:
  - country
  - picker
  - phone
  - input

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

#screenshots:
#  - description: 'Example of using the library.'
#    path: example.png

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter

  # Annotations
  meta: '^1.9.0'

  # Utilities
  collection: '^1.19.0'

dev_dependencies:
  # Integration tests for Flutter
  integration_test:
    sdk: flutter
  # Unit & Widget tests for Flutter
  flutter_test:
    sdk: flutter
  # Localization
  flutter_localizations:
    sdk: flutter

  # Linting
  flutter_lints: ^6.0.0

  # Code generation
  build_runner: ^2.4.15

  # Test utilities
  mockito: ^5.4.5

  # Logging
  l: ^5.0.1